version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/app/api"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "composer"
    directory: "/app/worker"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "npm"
    directory: "/app/frontend"
    schedule:
      interval: "weekly"
    target-branch: "dev"
